name: Publish Ignition Preview

on:
  workflow_dispatch:

env:
  NODE_VERSION: "18.x"

jobs:
  publish:
    env:
      SKIP_GENERATE_IGNITION_STATICS: true
      NEXT_PUBLIC_APP_URL: https://localhost:3000
      NEXT_PUBLIC_VERCEL_ENV: preview
      VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}

    runs-on: ubuntu-latest
    name: Publish Ignition

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Isolate Ignition
        run: mv packages/ignition .

      - name: Install packages
        working-directory: ./ignition
        run: npm install

      - name: Install Vercel CLI
        working-directory: ./ignition
        run: npm install vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: ./ignition
        run: npx vercel pull --yes --environment=${{ env.NEXT_PUBLIC_VERCEL_ENV }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Branch Name to Url
        id: branch-to-url
        run: |
          echo "URL_ID=$(echo "${{ github.head_ref }}" | tr -s ' ' | tr '[:upper:]' '[:lower:]' | sed 's,[ /],-,g')" >> $GITHUB_OUTPUT

      - name: Set NEXT_PUBLIC_APP_URL
        if: ${{ env.NEXT_PUBLIC_VERCEL_ENV != 'production' }}
        run: echo "NEXT_PUBLIC_APP_URL=https://${{ steps.branch-to-url.outputs.URL_ID }}" >> $GITHUB_ENV

      - name: Set Vercel Environment Variables
        if: ${{ env.NEXT_PUBLIC_VERCEL_ENV != 'production'}}
        continue-on-error: true
        working-directory: ./ignition
        run: |
          echo "${{ env.NEXT_PUBLIC_APP_URL }}" | npx vercel env add NEXT_PUBLIC_APP_URL ${{ env.NEXT_PUBLIC_VERCEL_ENV }} ${{ github.head_ref }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Ignition
        if: ${{ env.NEXT_PUBLIC_VERCEL_ENV != 'production' }}
        working-directory: ./ignition
        run: npx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Ignition to Vercel
        if: ${{ env.NEXT_PUBLIC_VERCEL_ENV != 'production' }}
        working-directory: ./ignition
        run: |
          url="$(npx vercel deploy --archive=tgz --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          npx vercel alias set "$url" ${{ steps.branch-to-url.outputs.URL_ID }} --token=${{ secrets.VERCEL_TOKEN }}

      - uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**The deployment is available on [Vercel](${{ env.NEXT_PUBLIC_APP_URL }}/)**.

              Deployment details:
                - ${{ env.NEXT_PUBLIC_APP_URL }}/`
            })
