# This workflow should publish a release for all packages in the monorepo that are correctly setup

name: Release Packages

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 18

permissions: write-all

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: $NODE_VERSION
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: $NODE_VERSION-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Test
        run: npm test

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' )
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: $NODE_VERSION-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Release
        run: npm run release
